[build]
  command = "npm run build && npm run export"
  publish = "out"
  functions = "netlify/functions"

[functions]
  included_files = [
    "netlify/functions/**",
    "netlify/functions/templates-dist/**"
  ]