[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/plantillas/**"]

[[redirects]]
  from = "/boda/*"
  to = "/boda/:splat"
  status = 200
