[[redirects]]
  from = "/boda/eugeyagus/"
  to = "/boda/eugeyagus/index.html"
  status = 200

[build]
  command = "npx puppeteer browsers install chrome && node generate-previews.js"
  publish = "."
  functions = ".netlify/functions"
