[build]
  command = "npm run build"
  publish = "out"

  [functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/boda/*"
  to = "/boda/:splat"
  status = 200
