[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[functions]
  included_files = ["plantillas/**"]
 

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/boda/*"
  to = "/boda/:splat"
  status = 200
