// src/config/countdownPresets.js

export const COUNTDOWN_PRESETS = [
  {
    id: "simple",
    nombre: "Simple",
    props: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 28,
      color: "#111111",
      showLabels: true,
      boxBg: "transparent",
      boxBorder: "transparent",
      boxRadius: 0,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "chips",
    nombre: "Chips",
    props: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 28,
      color: "#773dbe",
      showLabels: true,
      boxBg: "#ffffff",
      boxBorder: "#773dbe",
      boxRadius: 12,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "pill",
    nombre: "Píldoras",
    props: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 26,
      color: "#ffffff",
      showLabels: false,
      boxBg: "#773dbe",
      boxBorder: "transparent",
      boxRadius: 999,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "outline",
    nombre: "Outline",
    props: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 26,
      color: "#773dbe",
      showLabels: true,
      boxBg: "transparent",
      boxBorder: "#773dbe",
      boxRadius: 10,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "boxed",
    nombre: "Cajas",
    props: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 24,
      color: "#111111",
      showLabels: true,
      boxBg: "#f4f4f5",
      boxBorder: "#e4e4e7",
      boxRadius: 8,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "elegant-gold",
    nombre: "Elegante Dorado",
    props: {
      fontFamily: "'Great Vibes', cursive",
      fontSize: 28,
      color: "#b45309",
      showLabels: true,
      boxBg: "#fff8e1",
      boxBorder: "#facc15",
      boxRadius: 20,
      boxShadow: true,
      separator: "",
    },
  },
  {
    id: "dark-flip",
    nombre: "Flip Oscuro",
    props: {
      fontFamily: "'Roboto Mono', monospace",
      fontSize: 26,
      color: "#ffffff",
      showLabels: true,
      boxBg: "#111827",
      boxBorder: "#1f2937",
      boxRadius: 6,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "neon",
    nombre: "Neón",
    props: {
      fontFamily: "'Orbitron', sans-serif",
      fontSize: 28,
      color: "#0ff",
      showLabels: false,
      boxBg: "#000000",
      boxBorder: "#0ff",
      boxRadius: 8,
      boxShadow: true,
      separator: ":",
    },
  },
  {
    id: "pastel",
    nombre: "Pastel",
    props: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: 26,
      color: "#374151",
      showLabels: true,
      boxBg: "#fce7f3",
      boxBorder: "#f9a8d4",
      boxRadius: 14,
      boxShadow: false,
      separator: "",
    },
  },
  {
    id: "retro",
    nombre: "Retro Digital",
    props: {
      fontFamily: "'Press Start 2P', cursive",
      fontSize: 22,
      color: "#16a34a",
      showLabels: false,
      boxBg: "#000000",
      boxBorder: "#16a34a",
      boxRadius: 4,
      boxShadow: false,
      separator: ":",
    },
  },
  // ➕ Agregá estos al array COUNTDOWN_PRESETS

{
  id: "glassmorphism",
  nombre: "Glassmorphism",
  props: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: 24,
    color: "#ffffff",
    showLabels: true,
    boxBg: "rgba(255,255,255,0.2)",
    boxBorder: "rgba(255,255,255,0.4)",
    boxRadius: 16,
    boxShadow: true,
    separator: "",
  },
},
{
  id: "gradient-violet",
  nombre: "Gradiente Violeta",
  props: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 26,
    color: "#ffffff",
    showLabels: false,
    boxBg: "linear-gradient(135deg, #773dbe, #c084fc)",
    boxBorder: "transparent",
    boxRadius: 12,
    boxShadow: true,
    separator: ":",
  },
},
{
  id: "classic-blackwhite",
  nombre: "Clásico B/N",
  props: {
    fontFamily: "'Times New Roman', serif",
    fontSize: 28,
    color: "#000000",
    showLabels: true,
    boxBg: "#ffffff",
    boxBorder: "#000000",
    boxRadius: 0,
    boxShadow: false,
    separator: "/",
  },
},
{
  id: "soft-blue",
  nombre: "Azul Suave",
  props: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: 24,
    color: "#2563eb",
    showLabels: true,
    boxBg: "#dbeafe",
    boxBorder: "#3b82f6",
    boxRadius: 10,
    boxShadow: false,
    separator: "",
  },
},
{
  id: "cyberpunk",
  nombre: "Cyberpunk",
  props: {
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 26,
    color: "#f0f",
    showLabels: false,
    boxBg: "#000000",
    boxBorder: "#0ff",
    boxRadius: 4,
    boxShadow: true,
    separator: "|",
  },
},
{
  id: "luxury-blackgold",
  nombre: "Negro & Oro",
  props: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 28,
    color: "#facc15",
    showLabels: true,
    boxBg: "#111111",
    boxBorder: "#facc15",
    boxRadius: 14,
    boxShadow: true,
    separator: "",
  },
},
{
  id: "nature-green",
  nombre: "Naturaleza Verde",
  props: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: 24,
    color: "#166534",
    showLabels: true,
    boxBg: "#dcfce7",
    boxBorder: "#22c55e",
    boxRadius: 12,
    boxShadow: false,
    separator: "",
  },
},
{
  id: "romantic-pink",
  nombre: "Romántico Rosa",
  props: {
    fontFamily: "'Great Vibes', cursive",
    fontSize: 28,
    color: "#db2777",
    showLabels: true,
    boxBg: "#fce7f3",
    boxBorder: "#f472b6",
    boxRadius: 20,
    boxShadow: true,
    separator: "",
  },
},
{
  id: "ocean",
  nombre: "Oceánico",
  props: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: 24,
    color: "#0ea5e9",
    showLabels: true,
    boxBg: "#e0f2fe",
    boxBorder: "#38bdf8",
    boxRadius: 12,
    boxShadow: false,
    separator: ":",
  },
},
{
  id: "matrix",
  nombre: "Matrix",
  props: {
    fontFamily: "'Roboto Mono', monospace",
    fontSize: 24,
    color: "#22c55e",
    showLabels: false,
    boxBg: "#000000",
    boxBorder: "#22c55e",
    boxRadius: 2,
    boxShadow: false,
    separator: ":",
  },
},
];
