// src/config/textPresets.js
/**
 * 🎨 Presets de combinaciones de texto
 * Reglas:
 *  - Si una línea NO tiene x/dx => participa del centrado por grupo (center/right).
 *  - Si una línea tiene x o dx  => NO participa del centrado; se posiciona con ese offset.
 *  - dy es desplazamiento vertical relativo a baseY del preset.
 * Sugerencia: dejá ambos renglones sin dx cuando querés que queden perfectamente centrados entre sí.
 */

export const TEXT_PRESETS = [
    {
        id: "clasico",
        nombre: "Clásico elegante",
        // podés ajustar baseX/baseY si querés una posición inicial distinta
        // baseX: 120,
        // baseY: 140,
        gapY: 8,
        objetos: [
            {
                tipo: "texto",
                texto: "¡Nos Casamos!",
                fontSize: 42,
                fontFamily: "Great Vibes, cursive",
                color: "#773dbe",
                fontWeight: "normal",
                align: "center", // ⬅️ sin dx: participa del centrado por grupo
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Euge & Agus",
                fontSize: 24,
                fontFamily: "Montserrat, sans-serif",
                color: "#333333",
                fontWeight: "600",
                align: "center", // ⬅️ sin dx: queda centrado respecto al de arriba
                dy: 46,          // ~42*1.1 aprox de separación vertical
            },
        ],
    },

    {
        id: "moderno",
        nombre: "Moderno minimalista",
        gapY: 10,
        objetos: [
            {
                tipo: "texto",
                texto: "Nuestra boda",
                fontSize: 32,
                fontFamily: "Poppins, sans-serif",
                color: "#000000",
                fontWeight: "700",
                align: "left",  // ⬅️ sin dx: arranca en baseX
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "21 de Septiembre 2025",
                fontSize: 18,
                fontFamily: "Poppins, sans-serif",
                color: "#666666",
                fontWeight: "400",
                align: "left",
                dy: 38,         // ~32*1.1
            },
        ],
    },

    {
        id: "elegante",
        nombre: "Elegante dorado",
        gapY: 8,
        objetos: [
            {
                tipo: "texto",
                texto: "Euge & Agus",
                fontSize: 38,
                fontFamily: "Playfair Display, serif",
                color: "#b8860b",
                fontWeight: "700",
                align: "center", // ⬅️ sin dx: participa del centrado por grupo
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Recepción",
                fontSize: 20,
                fontFamily: "Montserrat, sans-serif",
                color: "#444444",
                fontWeight: "400",
                align: "center", // ⬅️ también sin dx: queda perfectamente centrado con el de arriba
                dy: 42,          // ~38*1.1
            },
        ],
    },

    {
        id: "minimal",
        nombre: "Minimal blanco y negro",
        objetos: [
            {
                tipo: "texto",
                texto: "Save the Date",
                fontSize: 28,
                fontFamily: "Helvetica, sans-serif",
                color: "#000000",
                fontWeight: "300",
                align: "center", // 1 sola línea: centrado simple
                dy: 0,
            },
        ],
    },

    {
        id: "romantico",
        nombre: "Romántico rosa",
        gapY: 6,
        objetos: [
            {
                tipo: "texto",
                texto: "Juntos por siempre",
                fontSize: 34,
                fontFamily: "Great Vibes, cursive",
                color: "#d6336c",
                fontWeight: "normal",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "María & Juan",
                fontSize: 20,
                fontFamily: "Montserrat, sans-serif",
                color: "#555555",
                fontWeight: "500",
                align: "center",
                dy: 38,
            },
        ],
    },

    {
        id: "artdeco",
        nombre: "Art Deco dorado",
        gapY: 10,
        objetos: [
            {
                tipo: "texto",
                texto: "Gran Fiesta",
                fontSize: 36,
                fontFamily: "Cinzel, serif",
                color: "#c5a100",
                fontWeight: "700",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "12 de Octubre",
                fontSize: 22,
                fontFamily: "Montserrat, sans-serif",
                color: "#333333",
                fontWeight: "400",
                align: "center",
                dy: 44,
            },
        ],
    },

    {
        id: "moderno-bold",
        nombre: "Moderno Bold",
        gapY: 12,
        objetos: [
            {
                tipo: "texto",
                texto: "Fiesta 2025",
                fontSize: 40,
                fontFamily: "Oswald, sans-serif",
                color: "#111111",
                fontWeight: "800",
                align: "left",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Sábado por la noche",
                fontSize: 18,
                fontFamily: "Roboto, sans-serif",
                color: "#555555",
                fontWeight: "400",
                align: "left",
                dx: 12,
                dy: 46,
            },
        ],
    },

    {
        id: "rustico",
        nombre: "Rústico natural",
        gapY: 6,
        objetos: [
            {
                tipo: "texto",
                texto: "Celebramos el Amor",
                fontSize: 30,
                fontFamily: "Shadows Into Light, cursive",
                color: "#5c3d2e",
                fontWeight: "normal",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Camila & Pedro",
                fontSize: 22,
                fontFamily: "Merriweather, serif",
                color: "#2e2e2e",
                fontWeight: "600",
                align: "center",
                dy: 36,
            },
        ],
    },

    {
        id: "minimal-invertido",
        nombre: "Minimal invertido",
        objetos: [
            {
                tipo: "texto",
                texto: "Save the Date",
                fontSize: 26,
                fontFamily: "Helvetica, sans-serif",
                color: "#ffffff",
                fontWeight: "400",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Ana & Leo",
                fontSize: 18,
                fontFamily: "Montserrat, sans-serif",
                color: "#ffffff",
                fontWeight: "300",
                align: "center",
                dy: 32,
            },
        ],
    },

    {
        id: "vintage",
        nombre: "Vintage clásico",
        gapY: 8,
        objetos: [
            {
                tipo: "texto",
                texto: "Gran Baile",
                fontSize: 34,
                fontFamily: "Cormorant Garamond, serif",
                color: "#7d5a50",
                fontWeight: "700",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Entrada libre",
                fontSize: 20,
                fontFamily: "Lora, serif",
                color: "#555555",
                fontWeight: "400",
                align: "center",
                dy: 40,
            },
        ],
    },

    {
        id: "urbano",
        nombre: "Urbano",
        gapY: 10,
        objetos: [
            {
                tipo: "texto",
                texto: "Party Time",
                fontSize: 36,
                fontFamily: "Anton, sans-serif",
                color: "#ff0055",
                fontWeight: "900",
                align: "left",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "DJ Live Session",
                fontSize: 20,
                fontFamily: "Roboto Condensed, sans-serif",
                color: "#222222",
                fontWeight: "500",
                align: "left",
                dx: 20,
                dy: 44,
            },
        ],
    },

    {
        id: "acuarela",
        nombre: "Acuarela suave",
        gapY: 6,
        objetos: [
            {
                tipo: "texto",
                texto: "Clara & Martín",
                fontSize: 32,
                fontFamily: "Dancing Script, cursive",
                color: "#2d6a4f",
                fontWeight: "400",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Un día especial",
                fontSize: 18,
                fontFamily: "Raleway, sans-serif",
                color: "#40916c",
                fontWeight: "300",
                align: "center",
                dy: 36,
            },
        ],
    },

    {
        id: "elegante-negro",
        nombre: "Elegante en negro",
        objetos: [
            {
                tipo: "texto",
                texto: "Cena de Gala",
                fontSize: 34,
                fontFamily: "Playfair Display, serif",
                color: "#000000",
                fontWeight: "700",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Hotel Majestic",
                fontSize: 20,
                fontFamily: "Montserrat, sans-serif",
                color: "#000000",
                fontWeight: "400",
                align: "center",
                dy: 42,
            },
        ],
    },

    {
        id: "tipografico",
        nombre: "Tipográfico contrastado",
        gapY: 12,
        objetos: [
            {
                tipo: "texto",
                texto: "FIESTA",
                fontSize: 40,
                fontFamily: "Oswald, sans-serif",
                color: "#1d3557",
                fontWeight: "900",
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "2025",
                fontSize: 28,
                fontFamily: "Roboto, sans-serif",
                color: "#e63946",
                fontWeight: "700",
                align: "center",
                dy: 48,
            },
        ],
    },
    {
        id: "boda-editorial-nocturno",
        nombre: "Boda editorial nocturno",
        categoria: "boda",
        tags: ["editorial", "moderno", "nocturno"],
        objetos: [
            {
                tipo: "texto",
                texto: "WE ARE GETTING MARRIED",
                fontSize: 16,
                fontFamily: "Montserrat, sans-serif",
                color: "#1f2937",
                fontWeight: "700",
                letterSpacing: 2.2,
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Sofia & Lucas",
                fontSize: 42,
                fontFamily: "Bodoni Moda, serif",
                color: "#111827",
                fontWeight: "700",
                align: "center",
                dy: 26,
            },
            {
                tipo: "texto",
                texto: "October 18, 2026",
                fontSize: 18,
                fontFamily: "Lato, sans-serif",
                color: "#6b7280",
                fontWeight: "400",
                letterSpacing: 0.8,
                align: "center",
                dy: 78,
            },
        ],
    },

    {
        id: "boda-soft-minimal",
        nombre: "Boda soft minimal",
        categoria: "boda",
        tags: ["minimal", "clean", "soft"],
        objetos: [
            {
                tipo: "texto",
                texto: "Our Wedding Day",
                fontSize: 20,
                fontFamily: "Poppins, sans-serif",
                color: "#475569",
                fontWeight: "500",
                letterSpacing: 1.1,
                align: "left",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Mia & Thiago",
                fontSize: 38,
                fontFamily: "Libre Bodoni, serif",
                color: "#0f172a",
                fontWeight: "700",
                align: "left",
                dy: 26,
            },
            {
                tipo: "texto",
                texto: "Sunset Garden Ceremony",
                fontSize: 16,
                fontFamily: "Raleway, sans-serif",
                color: "#64748b",
                fontWeight: "400",
                align: "left",
                dy: 70,
            },
        ],
    },

    {
        id: "boda-script-lux",
        nombre: "Boda script lux",
        categoria: "boda",
        tags: ["script", "luxury", "romantic"],
        objetos: [
            {
                tipo: "texto",
                texto: "Celebrate with us",
                fontSize: 18,
                fontFamily: "Cormorant Garamond, serif",
                color: "#9a7b4f",
                fontWeight: "600",
                letterSpacing: 1.2,
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Valentina & Mateo",
                fontSize: 44,
                fontFamily: "Allura, cursive",
                color: "#7c3f2d",
                fontWeight: "400",
                align: "center",
                dy: 20,
            },
            {
                tipo: "texto",
                texto: "A night to remember",
                fontSize: 17,
                fontFamily: "Nunito, sans-serif",
                color: "#6b7280",
                fontWeight: "500",
                align: "center",
                dy: 72,
            },
        ],
    },

    {
        id: "boda-kinetic-contrast",
        nombre: "Boda kinetic contrast",
        categoria: "boda",
        tags: ["kinetic", "bold", "contrast"],
        objetos: [
            {
                tipo: "texto",
                texto: "LOVE",
                fontSize: 54,
                fontFamily: "Bebas Neue, sans-serif",
                color: "#0f172a",
                fontWeight: "700",
                letterSpacing: 2,
                align: "left",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Ana + Bruno",
                fontSize: 28,
                fontFamily: "Dancing Script, cursive",
                color: "#be123c",
                fontWeight: "600",
                align: "left",
                dx: 52,
                dy: 46,
            },
            {
                tipo: "texto",
                texto: "06.12.2026",
                fontSize: 16,
                fontFamily: "Montserrat, sans-serif",
                color: "#334155",
                fontWeight: "700",
                letterSpacing: 1.8,
                align: "left",
                dx: 130,
                dy: 86,
            },
        ],
    },

    {
        id: "boda-cinematic-clean",
        nombre: "Boda cinematic clean",
        categoria: "boda",
        tags: ["cinematic", "clean", "modern"],
        objetos: [
            {
                tipo: "texto",
                texto: "Join the Celebration",
                fontSize: 17,
                fontFamily: "Lora, serif",
                color: "#475569",
                fontWeight: "500",
                align: "right",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Emma & Daniel",
                fontSize: 40,
                fontFamily: "Playfair Display, serif",
                color: "#111827",
                fontWeight: "700",
                align: "right",
                dy: 24,
            },
            {
                tipo: "texto",
                texto: "Ceremony at 5 PM",
                fontSize: 16,
                fontFamily: "Poppins, sans-serif",
                color: "#6b7280",
                fontWeight: "400",
                align: "right",
                dy: 72,
            },
        ],
    },

    {
        id: "boda-modern-serif-lines",
        nombre: "Boda modern serif lines",
        categoria: "boda",
        tags: ["serif", "modern", "editorial"],
        objetos: [
            {
                tipo: "texto",
                texto: "Together Forever",
                fontSize: 18,
                fontFamily: "Raleway, sans-serif",
                color: "#64748b",
                fontWeight: "600",
                letterSpacing: 2.1,
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Julieta & Simon",
                fontSize: 40,
                fontFamily: "Libre Bodoni, serif",
                color: "#0f172a",
                fontWeight: "700",
                align: "center",
                dy: 24,
            },
            {
                tipo: "texto",
                texto: "Saturday / City Hall",
                fontSize: 15,
                fontFamily: "Montserrat, sans-serif",
                color: "#64748b",
                fontWeight: "500",
                letterSpacing: 1,
                align: "center",
                dy: 72,
            },
        ],
    },

    {
        id: "boda-monochrome-chic",
        nombre: "Boda monochrome chic",
        categoria: "boda",
        tags: ["monochrome", "chic", "minimal"],
        objetos: [
            {
                tipo: "texto",
                texto: "Wedding Reception",
                fontSize: 18,
                fontFamily: "Poppins, sans-serif",
                color: "#334155",
                fontWeight: "600",
                align: "left",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Laura & Nicolas",
                fontSize: 40,
                fontFamily: "Cormorant Garamond, serif",
                color: "#020617",
                fontWeight: "700",
                align: "left",
                dy: 22,
            },
            {
                tipo: "texto",
                texto: "Black Tie Optional",
                fontSize: 15,
                fontFamily: "Nunito, sans-serif",
                color: "#475569",
                fontWeight: "500",
                align: "left",
                dy: 72,
            },
        ],
    },

    {
        id: "boda-bold-pop",
        nombre: "Boda bold pop",
        categoria: "boda",
        tags: ["bold", "pop", "playful"],
        objetos: [
            {
                tipo: "texto",
                texto: "BIG DAY",
                fontSize: 50,
                fontFamily: "Bebas Neue, sans-serif",
                color: "#111827",
                fontWeight: "700",
                letterSpacing: 2.5,
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Clara & Tomas",
                fontSize: 28,
                fontFamily: "Great Vibes, cursive",
                color: "#be123c",
                fontWeight: "400",
                align: "center",
                dy: 44,
            },
            {
                tipo: "texto",
                texto: "Dress in color",
                fontSize: 15,
                fontFamily: "Montserrat, sans-serif",
                color: "#1d4ed8",
                fontWeight: "600",
                letterSpacing: 0.8,
                align: "center",
                dy: 82,
            },
        ],
    },

    {
        id: "boda-luxe-bodoni",
        nombre: "Boda luxe bodoni",
        categoria: "boda",
        tags: ["luxury", "bodoni", "classic"],
        objetos: [
            {
                tipo: "texto",
                texto: "The Wedding",
                fontSize: 16,
                fontFamily: "Montserrat, sans-serif",
                color: "#7c2d12",
                fontWeight: "700",
                letterSpacing: 2.2,
                align: "center",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Renata & Franco",
                fontSize: 42,
                fontFamily: "Bodoni Moda, serif",
                color: "#111827",
                fontWeight: "700",
                align: "center",
                dy: 24,
            },
            {
                tipo: "texto",
                texto: "Palacio del Lago",
                fontSize: 16,
                fontFamily: "Lora, serif",
                color: "#6b7280",
                fontWeight: "500",
                align: "center",
                dy: 74,
            },
        ],
    },

    {
        id: "boda-future-romance",
        nombre: "Boda future romance",
        categoria: "boda",
        tags: ["future", "romance", "modern"],
        objetos: [
            {
                tipo: "texto",
                texto: "SAVE THE DATE",
                fontSize: 18,
                fontFamily: "Montserrat, sans-serif",
                color: "#0f172a",
                fontWeight: "700",
                letterSpacing: 2.8,
                align: "left",
                dy: 0,
            },
            {
                tipo: "texto",
                texto: "Noa & Elias",
                fontSize: 38,
                fontFamily: "Sacramento, cursive",
                color: "#8b5cf6",
                fontWeight: "400",
                align: "left",
                dx: 24,
                dy: 30,
            },
            {
                tipo: "texto",
                texto: "11 / 27 / 2026",
                fontSize: 16,
                fontFamily: "Poppins, sans-serif",
                color: "#334155",
                fontWeight: "600",
                letterSpacing: 1.4,
                align: "left",
                dx: 76,
                dy: 74,
            },
        ],
    },
];
